import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...await page.locator('html').click();
  // Create
await page.goto('http://localhost:8080/');
await page.goto('http://localhost:8080/#/');
await page.goto('http://localhost:8080/#/songs');
await page.getByRole('link', { name: 'add' }).click();
await page.getByLabel('Title').click();
await page.getByLabel('Title').fill('AC/DC - Highway to Hell');
await page.getByLabel('Title').click();
await page.getByLabel('Title').click();
await page.getByLabel('Title').click();
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowLeft');
await page.getByLabel('Title').press('ArrowRight');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Shift+ArrowLeft');
await page.getByLabel('Title').press('Control+x');
await page.locator('div').filter({ hasText: /^Artist$/ }).click();
await page.getByLabel('Artist').fill('AC/DC - ');
await page.getByLabel('Genre').click();
await page.getByLabel('Genre').fill('rok');
await page.locator('div').filter({ hasText: /^Album$/ }).click();
await page.getByLabel('Album', { exact: true }).fill('Test');
await page.getByLabel('Album Image Url').click();
await page.getByLabel('Album Image Url').fill('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.sonymusic.co.uk%2Fartist%2Facdc%2F&psig=AOvVaw0DOvDAQxwzTXHxG7vgKBgC&ust=1701520953014000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJj729Oh7oIDFQAAAAAdAAAAABAE');
await page.getByLabel('YouTube ID').click();
await page.getByLabel('YouTube ID').fill('https://youtu.be/l482T0yNkeo?si=wUUOuIhqYg0pBeSs');
await page.getByLabel('Tab').click();
await page.locator('div').filter({ hasText: /^Tab$/ }).locator('div').nth(1).click();
await page.getByLabel('Tab').click();
await page.getByLabel('Tab').fill('Testing');
await page.getByLabel('Lyrics').click();
await page.getByLabel('Lyrics').fill('Livin\' easy\nLovin\' free\nSeason ticket on a one way ride\nAskin\' nothin\'\nLeave me be\nTakin\' everythin\' in my stride\nDon\'t need reason\nDon\'t need rhyme\nAin\'t nothin\' that I\'d rather do\nGoin\' down\nParty time\nMy friends are gonna be there too\nI\'m on the highway to hell\nOn the highway to hell\nHighway to hell\nI\'m on the highway to hell\nNo stop signs\nSpeed limit\nNobody\'s gonna slow me down\nLike a wheel\nGonna spin it\nNobody\'s gonna mess me around\nHey satan\nPayin\' my dues\nPlayin\' in a rockin\' band\nHey mumma\nLook at me\nI\'m on the way to the promised land\nI\'m on the highway to hell\nHighway to hell\nI\'m on the highway to hell\nHighway to hell\nDon\'t stop me\nI\'m on the highway to hell\nOn the highway to hell\nHighway to hell\nI\'m on the highway to hell\n(Highway to hell) I\'m on the highway to hell\n(Highway to hell) highway to hell\n(Highway to hell) highway to hell\n(Highway to hell)\nAnd I\'m goin\' down\nAll the way\nI\'m on the highway to hell');
await page.getByRole('button', { name: 'Create Song' }).click();
});

test('test2', async ({ page }) => {
// Edit 
await page.goto('http://localhost:8080/');
await page.goto('http://localhost:8080/#/');
await page.goto('http://localhost:8080/#/songs');
await page.locator('.flex > .cyan').first().click();
await page.getByRole('link', { name: 'Edit' }).click();
await page.getByRole('button', { name: 'Save Song' }).click();
await page.getByLabel('Lyrics').click();
await page.getByLabel('Lyrics').fill('somthing');
await page.getByLabel('Tab').click();
await page.getByLabel('Tab').fill('cool');
await page.getByLabel('Lyrics').click({button: 'right'});
await page.getByLabel('Lyrics').click();
await page.getByLabel('Lyrics').click();
await page.getByLabel('Lyrics').press('ArrowLeft');
await page.getByLabel('Lyrics').press('ArrowLeft');
await page.getByLabel('Lyrics').press('ArrowLeft');
await page.getByLabel('Lyrics').press('ArrowLeft');
await page.getByLabel('Lyrics').press('ArrowLeft');
await page.getByLabel('Lyrics').fill('something');
await page.getByRole('button', { name: 'Save Song' }).click();
});
